### ISSUE TITLE
Create a Top Menu/Navigation Bar

### ISSUE THREAD

**Issue by zghera** [googleinterns/step53-2020#9]
### Issue summary

Create a navigation/menu bar that will be displayed as a banner at the top of all pages except the landing page. This could allow users to navigate to different portions of the website, see their user profile page, logout, Slurp logo, etc. See current visual prototype [here](https://www.figma.com/file/ZunMOqg1XTQpZ9EIMFGSP5/Top-Navigation%2FMenu-Bar).

### Expected behavior

n/a

### Actual behavior

n/a

### Steps to reproduce (including any preconditions)

n/a

### Screenshot/screencast of this problem (if possible)

n/a

### Your environment

n/a

**Comment by keiffer01** [comment]
I could take this up since user profile and logout link will likely need to be placed in this header. I can put logout/profile stuff on the right side of the header and leave the rest of it as a template for whatever the current page needs it for.

**Comment by zghera** [comment]
> I could take this up since user profile and logout link will likely need to be placed in this header. I can put logout/profile stuff on the right side of the header and leave the rest of it as a template for whatever the current page needs it for.

Yeah that sounds good!
